name-template: 'Go SDK v$RESOLVED_VERSION'
tag-template: 'sdk/go/v$RESOLVED_VERSION'
tag-prefix: 'sdk/go/v'
categories:
  - type: 'pre-include'
    when:
      paths:
        - 'sdk/**'
        - 'docs/sdk/**'
        - '.github/workflows/sdk-ci.yml'
        - '.github/workflows/sdk-release.yml'
        - '.github/workflows/sdk-release-drafter.yml'
        - '.github/release-drafter-sdk.yml'
  - title: 'Breaking Changes 🔥'
    semver-increment: major
    when:
      label: 'breaking-change'
  - title: 'New Features 🎉'
    semver-increment: minor
    when:
      labels:
        - 'feature'
  - title: 'Improvements 🔝'
    semver-increment: minor
    when:
      labels:
        - 'enhancement'
  - title: 'Bug Fixes 🐛'
    semver-increment: patch
    when:
      labels:
        - 'bug'
  - title: 'Updated Dependencies 🔒'
    semver-increment: patch
    when:
      label: 'dependencies'
  - title: 'Documentation 📚'
    semver-increment: patch
    when:
      label: 'documentation'
  - title: 'Deprecations 🧹'
    semver-increment: minor
    when:
      label: 'deprecations'
  - title: 'CI 🤖'
    semver-increment: patch
    when:
      label: 'ci'
  - title: 'Other Changes 🛠️'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

template: |
  ## Go SDK

  $CHANGES
