secret:
  mode: create
  data:
    databasePassword: openlicensd
    bootstrapAdminPasswordHash: $2a$10$w6lsMGg4BZVLWv0dqUXT2eUWcWhbh99FIECbPlBNeE.pu089T5E/2

config:
  database:
    host: postgres
    port: 5432
    name: openlicensd
    user: openlicensd
    sslmode: disable
  bootstrapAdmin:
    email: admin@example.com
